[package]
authors = ["Zhang Li <richox@qq.com>"]
build = "src/build.rs"
edition = "2018"
name = "orz"
version = "1.5.0"
[dependencies]
byteorder = "1.3"
log = "0.4.6"
simplelog = "0.6.0"
structopt = "0.2"
unchecked-index = "0.2.2"

[profile]
[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = true
opt-level = 3
overflow-checks = false
panic = "abort"
