[package]
name = "orz"
version = "1.2.0"
authors = ["Zhang Li <richox@qq.com>"]
build = "src/build.rs"

[dependencies]
byteorder = "1.2"
structopt = "0.2"
unchecked-index = "0.2.2"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = "abort"
incremental = false
overflow-checks = false
