[package]
name = "orz"
version = "1.5.0"
authors = ["Zhang Li <richox@qq.com>"]
build = "src/build.rs"
edition = "2018"

[dependencies]
byteorder = "1.3"
structopt = "0.2"
unchecked-index = "0.2.2"
log = "0.4.6"
simplelog = "0.6.0"

[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false
codegen-units = 1
panic = "abort"
incremental = false
overflow-checks = false
